# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g <- function(x, xi, u) {
    .Call('_monotoneSIM_g', PACKAGE = 'monotoneSIM', x, xi, u)
}

update_beta <- function(y, X, xi, beta_init, u, sigma_sq_eps, sigma_sq_beta = 10000.0) {
    .Call('_monotoneSIM_update_beta', PACKAGE = 'monotoneSIM', y, X, xi, beta_init, u, sigma_sq_eps, sigma_sq_beta)
}

