# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

monotoneSIM_c <- function(y, X, beta_init, xi_init, Sigma_xi, u, monotone, n_HMC, sigma_sq_beta, sigma_sq_eps_init, a_eps, b_eps, M_burn, M) {
    .Call(`_monotoneSIM_monotoneSIM_c`, y, X, beta_init, xi_init, Sigma_xi, u, monotone, n_HMC, sigma_sq_beta, sigma_sq_eps_init, a_eps, b_eps, M_burn, M)
}

g_mtx <- function(xi_mtx, grid_x, u) {
    .Call(`_monotoneSIM_g_mtx`, xi_mtx, grid_x, u)
}

